server:
  port: 8000
spring:
  application:
    name: GATEWAY
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      consul:
        host: localhost
        port: 8500
        enabled: true
        discovery:
           query-passing: true

    gateway:
      routes:
        - id: STUDENT-SERVICE
          #uri: http://localhost:8080/
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**,/items/**,/receipt/**,/receiptInfo/**,/studentItemsReceipt/**

      globalcors:
        #add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
        default-filters:
          - name: Retry
            args:
              retries: 3
              methods: GET,POST

#logging:
#  level:
#    org:
#      hibernate: 'DEBUG '
#      springframework:
#        web: DEBUG