server:
  port: 8000
spring:
  application:
    name: gateway
  config:
    import: 'consul:'
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      consul:
        host: localhost
        port: 8500
        enabled: true
        discovery:
           query-passing: true

    gateway:
      routes:
        - id: student
          #uri: http://localhost:8080/
          uri: lb://student
          predicates:
            - Path=/student/**,/items/**,/receipt/**,/receiptInfo/**,/studentItemsReceipt/**

      globalcors:
        #add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
        default-filters:
          - name: Retry
            args:
              retries: 3
              methods: GET,POST

amqp:
  exchange:
    items: myqueue

#logging:
#  level:
#    org:
#      hibernate: 'DEBUG '
#      springframework:
#        web: DEBUG

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG
            connection:
              CachingConnectionFactory: WARN

management:
  tracing:
    sampling:
      probability: 1.0
